touch "hello.txt"
echo "This is some new content to add......" >> "hello.txt"
echo "my name is harshit nigam.."
echo "grep in process.."
grep "harshit" "hello.txt"
echo "sed is in process to replace old_string"
sed 's/old_string/new_string/g' "hello.txt"
echo "awak is in proces to print line 2 and 3"
awk '{print $2, $1}' "hello.txt"
